<?php
/**
 * Created by PhpStorm.
 * User: veades
 * Date: 2014-12-04
 * Time: 7:04 PM
 *
 * @file
 * Module provides af field format that turns the field output into an accordion markup.
 */

/**
 * Implementation of hook_preprocess_page().
 */
function ubc_accordion_preprocess_page(&$variables) {
    $path = drupal_get_path('module', 'ubc_accordion');
    drupal_add_js($path . '/js/ubc_accordion.js');
}

/**
 * Implements hook_field_formatter_info().
 */
function ubc_accordion_field_formatter_info() {

    return array(
        'ubc_accordion_formatter'=>array(
            'label' => t('Accordion'),
            'description' => t('Outputs the field as accordion, with label as tab'),
            'field types' => array('text','text_long','text_with_summary','taxonomy_term_reference'),
            //'settings' => array(),
        ),

    );
}


/**
 * Implements hook_field_formatter_view().
 */
function ubc_accordion_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {

    $element = array();
    $internal = '';

    if(!empty($items)){

        foreach ($items as $delta => $item) {
            $internal = $item['value'];
        }

        $tab_label = $instance['label'];

        $markup = <<<EOD
        <div class="accordion">
            <div class="accordion-tab" tabindex="0">$tab_label</div>
            <div class="accordion-content clearfix" style="display: none; ">$internal</div>
        </div>
EOD;

        //watchdog('ubc_accordion',"Accordion label is  $tab_label and internal is $internal");
        $element[0]['#markup'] = $markup;
    }

    return $element;
}




